name: Build and Deploy Web App

on:
  push:
    branches:
      - devops

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build Angular SSR
        run: npm run build
        
      - name: Docker Build and Deploy
        run: |
          cd /home/cse438/trendyol-clone
          docker compose build --no-cache web
          docker compose up -d --force-recreate web

